/**
 * GET /api/admin/health
 *
 * Returns the latest health-report.json generated by scripts/health-check.ts.
 * Protected by ADMIN_SECRET env var when set (Bearer token).
 */

import { NextRequest, NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest) {
  const secret = process.env.ADMIN_SECRET;
  if (secret) {
    const auth = req.headers.get("authorization");
    if (auth !== `Bearer ${secret}`) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
  }

  try {
    const reportPath = path.join(process.cwd(), "src/data/health-report.json");
    const raw = fs.readFileSync(reportPath, "utf-8");
    const report = JSON.parse(raw);
    return NextResponse.json(report);
  } catch {
    return NextResponse.json({ error: "Health report not yet generated. Run: npx tsx scripts/health-check.ts" }, { status: 404 });
  }
}
